spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

sns:
  youtube:
    url: https://www.googleapis.com/youtube/v3/videos
    key: ${YOUTUBE_API_KEY}