spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

sns:
  url:
    youtube: https://www.googleapis.com/youtube/v3/videos
  key:
    youtube: ${YOUTUBE_API_KEY}
